SELECT TOP 10 * FROM dbo.customer_shopping_behavior;
--Q1 total revenue generated by male vs female
select Gender, SUM(Purchase_Amount_USD)as revenue
from customer_shopping_behavior
group by Gender
---Q2 which customer used a discount but still spent more than the average purchase amount?
SELECT Customer_ID, Purchase_Amount_USD
FROM customer_shopping_behavior
WHERE Discount_Applied = 'Yes'
AND Purchase_Amount_USD >= (
    SELECT AVG(Purchase_Amount_USD)
    FROM customer_shopping_behavior
);

-- Q3 which are the top 5 products with the highest average review rating?
select  top 5 Item_Purchased, ROUND(AVG(Review_Rating),2) as "Average Product Rating"
from customer_shopping_behavior
group by Item_Purchased
order by AVG(Review_Rating) desc

---Q4 compare the average purchase amount between standard and express shipping
select Shipping_Type,
ROUND(AVG(Purchase_Amount_USD), 2)
from customer_shopping_behavior
where Shipping_Type in ('Standard','Express')
group by Shipping_Type

--Q5 Do subscribed customers spend more?
--👉 Compare:
--Average spend
--Total revenue
--between:
--Subscribers
--Non-subscribers
SELECT 
    Subscription_Status,
    COUNT(*) AS total_customers,
    ROUND(AVG(Purchase_Amount_USD), 2) AS avg_spend,
    ROUND(SUM(Purchase_Amount_USD), 2) AS total_revenue
FROM customer_shopping_behavior
GROUP BY Subscription_Status;

-- Add percentage contribution:
SELECT 
    Subscription_Status,
    ROUND(SUM(Purchase_Amount_USD) * 100.0 / 
        (SELECT SUM(Purchase_Amount_USD) FROM customer_shopping_behavior),2) 
    AS revenue_percentage
FROM customer_shopping_behavior
GROUP BY Subscription_Status;

--- Which gender spends more?
SELECT 
    Gender,
    ROUND(AVG(Purchase_Amount_USD), 2) AS avg_spend,
    ROUND(SUM(Purchase_Amount_USD), 2) AS total_spend
FROM customer_shopping_behavior
GROUP BY Gender
ORDER BY avg_spend DESC;



-- Q6 which 5 products have the highest % of purchases with discounts applied
SELECT TOP 5
    Item_Purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE WHEN Discount_Applied = 'Yes' THEN 1 ELSE 0 END) AS discount_purchases,
    
    CAST(
        ROUND(
            SUM(CASE WHEN Discount_Applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 
            / COUNT(*), 
        2)
    AS DECIMAL(5,2)) AS discount_percentage

FROM customer_shopping_behavior
GROUP BY Item_Purchased
ORDER BY discount_percentage DESC;

---Question Q7
--👉 Segment customers into:
--New
--Returning
--Loyal
---👉 Based on:
---👉 total number of previous purchases
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        purchase_amount_usd,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS segment
    FROM customer_shopping_behavior
)
SELECT 
    segment,
    ROUND(AVG(purchase_amount_usd),2) AS avg_spend,
    SUM(purchase_amount_usd) AS total_spend
FROM customer_type
GROUP BY segment;

-- Q8 what are the top 3 purchased products by each category
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
        
    FROM customer_shopping_behavior
    GROUP BY category, item_purchased
)

SELECT 
    category,
    item_purchased,
    total_orders,
    item_rank
FROM item_counts
WHERE item_rank <= 3;

--Q9 👉 Are repeat buyers (>5 previous purchases) more likely to subscribe?
SELECT 
    Subscription_Status,
    COUNT(*) AS total_customers,
    
    ROUND(
        COUNT(*) * 100.0 / 
        SUM(COUNT(*)) OVER (), 
    2)  AS percentage
    
FROM customer_shopping_behavior
WHERE previous_purchases > 5
GROUP BY Subscription_Status;


--## same Q9

SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Others'
    END AS customer_type,
    
    Subscription_Status,
    COUNT(*) AS total_customers
    
FROM customer_shopping_behavior
GROUP BY 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Others'
    END,
    Subscription_Status;

    ---Q9 
SELECT 
    customer_type,
    ROUND(
        SUM(CASE WHEN Subscription_Status = 'Yes' THEN 1 ELSE 0 END) * 100.0 
        / COUNT(*), 
    2) AS subscription_rate
FROM (
    SELECT 
        CASE 
            WHEN previous_purchases > 5 THEN 'Repeat Buyers'
            ELSE 'Others'
        END AS customer_type,
        Subscription_Status
    FROM customer_shopping_behavior
) t
GROUP BY customer_type;


--- what is the revenue contribution of each age group

SELECT 
    age_group,
    SUM(Purchase_Amount_USD) AS total_revenue,
    
    ROUND(
        SUM(Purchase_Amount_USD) * 100.0 / 
        (SELECT SUM(Purchase_Amount_USD) FROM customer_shopping_behavior),
    2) AS revenue_percentage

FROM (
    SELECT 
        Purchase_Amount_USD,
        
        CASE 
            WHEN Age < 25 THEN 'Young'
            WHEN Age BETWEEN 25 AND 40 THEN 'Adult'
            ELSE 'Senior'
        END AS age_group
        
    FROM customer_shopping_behavior
) AS t

GROUP BY age_group
ORDER BY revenue_percentage DESC;


---
SELECT 
    age_group,
    Subscription_Status,
    SUM(Purchase_Amount_USD) AS revenue
FROM (
    SELECT 
        Purchase_Amount_USD,
        Subscription_Status,
        CASE 
            WHEN Age < 25 THEN 'Young'
            WHEN Age BETWEEN 25 AND 40 THEN 'Adult'
            ELSE 'Senior'
        END AS age_group
    FROM customer_shopping_behavior
) t
GROUP BY age_group, Subscription_Status;

